# -------------------------------------------------------------------------
# lmm2.R
# Linear Mixed-Effects Models -- Physiology ~ Fear * Arachnophobia
#
# Purpose:
# 
#   - Fit LMMs examining whether trial-level fear rating_cwcs and participant-level;
#   - arachnophobia scores (and their interaction) predict physiological;
#   - responses across eight dependent variables.
#
# Design:
# 
#   - Level 1 (trial): fear_rating_cwc_cwc (within-person centered);
#   - Level 2 (participant): psychometric scales (grand-mean standardized);
#   - Cross-level interaction tested in a separate model set.
#
# Random structure:
# 
#   Selected parsimoniously via likelihood-ratio tests comparing:
#   
#     - (1) intercepts only;
#     - (2) random slope without correlation;
#     - (3) random slope with correlation.
#
# Outputs:
# 
#   - ./output/lmm.xlsx (3 different sheets)
# -------------------------------------------------------------------------

library(tidyverse)    
library(lmerTest)     
library(broom.mixed)  
library(glue)         
library(writexl)      



# Data Import -------------------------------------------------------------

# Data generated by lmm.R

data <- read.csv("./output/final_consolidated_data.csv")



# Dependent Variables -----------------------------------------------------

# Will probably be exported to a config.R in the future.

dvs <- c(
  "bpm_ecg",             # Heart rate (beats per minute, ECG-derived)
  "rmssd",               # Root mean square of successive RR differences
  "cardiac_deceleration",# Deceleration component of cardiac response
  "scr_amplitude",       # Skin conductance response amplitude
  "resp_std",            # Respiratory signal standard deviation
  "pupil_diam_raw",      # Raw pupil diameter
  "pupil_dilation_speed",# Rate of pupil dilation
  "gaze_dispersion"      # Spatial dispersion of gaze
)



# Predictor Centering -----------------------------------------------------

# Group-mean centering (within-person) for the trial-level fear rating_cwc:
# 
# - rating_cwc separates within-person variation (L1) from the
# - participant mean (L2), preventing conflation of between- and 
#     within-person effects.
#
# Grand-mean standardization for psychometric scales:
# 
# - Standardized scores allow effect-size comparison across
# - instruments with different scales.

data <- data |>
  group_by(participant_id) |>
  mutate(
    rating_cwc = rating - mean(rating, na.rm = TRUE),   # within
    rating_pm  = mean(rating, na.rm = TRUE)             # between-person mean
  ) |>
  ungroup() |>
  mutate(
    rating_cwc_z = as.numeric(scale(rating_cwc)),
    rating_pm_z  = as.numeric(scale(rating_pm))
  ) |> 
  mutate(
    across(
      c(FSQ_pre, SAS_pre, SPQ, STAI),
      ~ scale(.x)[, 1],
      .names = "{.col}_z"
    )
  )



# Parsimonious Random-Structure Selection ---------------------------------

# Random structure is
# chosen via sequential LRT (alpha = .05):
# 
# - Step A: Does adding a random slope improve fit over intercepts only?
# - Step B: Does adding the slope–intercept correlation improve fit further?
#
# Arguments:
# 
# - m_simple  lmer object with random intercepts only
# - m_pente   lmer object with random slope (no correlation)
# - m_full    lmer object with random slope + intercept–slope correlation
#
# Returns a list with:
# 
# - $formula -> formula of the selected model
# - $type -> human-readable label of the selected structure

select_best_model <- function(m_simple, m_pente, m_full) {

  p_slope <- anova(m_simple, m_pente)[["Pr(>Chisq)"]][2]

  if (is.na(p_slope) || p_slope >= 0.05) {
    return(list(
      formula = formula(m_simple),
      type    = "Simple (intercepts only)"
    ))
  }

  p_corr <- anova(m_pente, m_full)[["Pr(>Chisq)"]][2]

  # Include correlation only if it significantly improves fit
  if (!is.na(p_corr) && p_corr < 0.05) {
    list(formula = formula(m_full),  type = "Full (intercept + slope + corr)")
  } else {
    list(formula = formula(m_pente), type = "Slope (intercept + slope, no corr)")
  }
}



# Main Effects of Psychometric Scales (Between-Person) --------------------

# Do individuals who score higher on arachnophobia measures show globally 
#   stronger physiological responses, independent of trial-level fear?
# 
# Model: DV ~ fear_rating_cwc_cwc + PSY_z + {random_structure}
#
# fear_rating_cwc_cwc is included as a covariate to partial out within-trial
#   variance before estimating the between-person PSY effect.
#
# Arguments:
# 
# - dv_name   Name of the dependent variable column. <chr>
# - psy_name  Name of the standardized psychometric predictor. <chr>
# - df        Data frame containing all variables.
#
# Returns:
# 
# - Tibble of fixed-effect estimates (excluding the intercept) with
# - model metadata columns appended.

run_lmm_main_effect <- function(dv_name, psy_name, df) {

  make_formula <- function(random_spec) {
    as.formula(glue("{dv_name} ~ rating_cwc_z + rating_pm_z + {psy_name} + {random_spec}"))
  }

  f_simple <- make_formula("(1 | participant_id) + (1 | picture_id)")
  f_slope  <- make_formula("(1 | picture_id) + (0 + rating_cwc | participant_id)")
  f_full   <- make_formula("(1 | picture_id) + (1 + rating_cwc | participant_id)")

  fit <- function(f) lmer(f, data = df, REML = FALSE)

  best      <- select_best_model(fit(f_simple), fit(f_slope), fit(f_full))
  best_reml <- lmer(best$formula, data = df, REML = TRUE)

  best_reml |>
    tidy(conf.int = TRUE) |>
    filter(effect == "fixed", term != "(Intercept)") |>
    mutate(
      dependent_var      = dv_name,
      psychometric       = psy_name,
      model_type         = "main_effect",
      selected_structure = best$type
    ) |>
    select(
      dependent_var, psychometric, model_type, selected_structure,
      term, estimate, std.error, p.value, conf.low, conf.high
    )
}



# Cross-Level Interaction (Trial-Level * Between-Person) ------------------

# Research question:
# 
# 
# Is the trial-by-trial effect of fear on physiology stronger in individuals
#   with higher arachnophobia scores?
#   
#
# Model: DV ~ fear_rating_cwc_cwc * PSY_z + {random_structure}
#
# The interaction term (fear_rating_cwc_cwc:PSY_z) tests whether the L1 slope
#   varies as a function of the L2 psychometric score.

run_lmm_interaction <- function(dv_name, psy_name, df) {

  make_formula <- function(random_spec) {
    as.formula(glue("{dv_name} ~ rating_cwc * {psy_name} + rating_pm_z + {random_spec}"))
  }

  f_simple <- make_formula("(1 | participant_id) + (1 | picture_id)")
  f_slope  <- make_formula("(1 | picture_id) + (0 + rating_cwc | participant_id)")
  f_full   <- make_formula("(1 | picture_id) + (1 + rating_cwc | participant_id)")

  fit <- function(f) lmer(f, data = df, REML = FALSE)

  best      <- select_best_model(fit(f_simple), fit(f_slope), fit(f_full))
  best_reml <- lmer(best$formula, data = df, REML = TRUE)

  best_reml |>
    tidy(conf.int = TRUE) |>
    filter(effect == "fixed", term != "(Intercept)") |>
    mutate(
      dependent_var      = dv_name,
      psychometric       = psy_name,
      model_type         = "interaction",
      selected_structure = best$type
    ) |>
    select(
      dependent_var, psychometric, model_type, selected_structure,
      term, estimate, std.error, p.value, conf.low, conf.high
    )
}



# Execution ---------------------------------------------------------------

# Builds a data frame containing all possible combinations of psychometric scales
#   and dependent variables.
#   
# Iterates on those combinations with run_lmm_main_effect().
# 
# Iterates on those combinations with run_lmm_interaction().
# 
# Combines results in a single data frame.

psy_scales <- c("FSQ_pre_z", "SAS_pre_z", "SPQ_z", "STAI_z")

combinations <- expand_grid(dv = dvs, psy = psy_scales)

results_main <- combinations |>
  mutate(results = map2(dv, psy, run_lmm_main_effect, df = data)) |>
  unnest(results) |>
  select(-dv, -psy) |>
  mutate(across(where(is.numeric), \(x) round(x, digits = 3))) |> 
  mutate(p_fdr = p.adjust(p.value, method = "BH")) |> 
  mutate(across(where(is.numeric), \(x) round(x, digits = 3)))

results_interaction <- combinations |>
  mutate(results = map2(dv, psy, run_lmm_interaction, df = data)) |>
  unnest(results) |>
  select(-dv, -psy) |>
  mutate(across(where(is.numeric), \(x) round(x, digits = 3))) |> 
  mutate(p_fdr = p.adjust(p.value, method = "BH")) |> 
  mutate(across(where(is.numeric), \(x) round(x, digits = 3)))

results_all <- bind_rows(results_main, results_interaction) |>
  mutate(across(where(is.numeric), \(x) round(x, 3))) |>
  arrange(model_type, dependent_var, psychometric, term) |> 
  mutate(p_fdr = p.adjust(p.value, method = "BH")) |> 
  mutate(across(where(is.numeric), \(x) round(x, digits = 3)))



# Console Output ----------------------------------------------------------

# Provides useful insights regarding the results, as well as the results
#   themselves.

cat("\n── Selected Random Structures ──\n")
results_all |>
  distinct(dependent_var, psychometric, model_type, selected_structure) |>
  print(n = Inf)

cat("\n── Full Results ──\n")
print(results_all, n = Inf)

cat("\n── Psychometric Scale Comparison by DV ──\n")
results_all |>
  filter(
    model_type == "main_effect",
    term %in% psy_scales
  ) |>
  select(dependent_var, psychometric, estimate, std.error, p.value) |>
  arrange(dependent_var, p.value) |>
  print(n = Inf)



# Export ------------------------------------------------------------------

# Generate an XLSX file with one sheet per results.

results <- list(
  "stats_finales"       = results_all,
  "results_main"        = results_main,
  "results_interaction" = results_interaction
)

writexl::write_xlsx(x = results, path = "./output/lmm.xlsx") 
